[workspace]
members = [
    "packages/event-store",
    "packages/loadbalancer",
    "packages/common",
    "packages/service",
    "packages/north",
    "packages/core",
    "packages/cqrs",
    "examples/basic",
]